feedback_system/staff_sessions/urls.py
from django.urls import path

from . import views

#this sets the application namespace so that the {% url %} template tag
#creates links based of the names in this file  for this app
#might be mutliple urls with name='detail' across the project
app_name= 'staff_sessions'

#name variable is used to refer to URls to make links in view templates
urlpatterns = [
    #/staff/login/
    path('login/', views.login, name='login'),
    #/staff/logout/
    path('logout/', views.logout, name='logout'),
    #/staff/lectures/
    path('lectures/', views.index, name='index'),
    #/staff/lectures/new/
    path('lectures/new/', views.lecture_new, name='lecture_new'),
    #/staff/lectures/delete/?
    path('lectures/delete/<int:id>/', views.lecture_delete, name='lecture_delete'),
]

feedback_system/templates/staff/lecture_new.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block title %}{% trans "New Lecture" %}{% endblock %}

{% block nav_options %}
<div>
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item">
      <a class="nav-link border-right border-white p-3" href="{% url 'staff:index' %}" role="button">{% trans "Lecture History" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link border-left border-white p-3" href="{% url 'staff:logout' %}" role="button">{% trans "Logout" %}</a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="container p-3">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-8">
      <form action="{% url 'staff:lecture_new' %}" method="post" class="bg-light border rounded p-2">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-default">
            {% trans "Create" %}
          </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-auto">
      <form action="{% url 'staff:lecture_new' %}" method="post" enctype="multipart/form-data" class="bg-light border rounded p-2">
        {% csrf_token %}
        {% bootstrap_form pdf_form %}
        {% buttons %}
          <button type="submit" class="btn btn-default">
            {% trans "Extract" %}
          </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-danger text-center" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}