feedback_system/staff_sessions/urls.py
from django.urls import path

from . import views

#this sets the application namespace so that the {% url %} template tag
#creates links based of the names in this file  for this app
#might be mutliple urls with name='detail' across the project
app_name= 'staff_sessions'

#name variable is used to refer to URls to make links in view templates
urlpatterns = [
    #/staff/login/
    path('login/', views.login, name='login'),
    #/staff/logout/
    path('logout/', views.logout, name='logout'),
    #/staff/lectures/
    path('lectures/', views.index, name='index'),
    #/staff/lectures/new/
    path('lectures/new/', views.lecture_new, name='lecture_new'),
    #/staff/lectures/delete/?
    path('lectures/delete/<int:id>/', views.lecture_delete, name='lecture_delete'),
]

feedback_system/staff_sessions/models.py
import random
import string
from django.db import models
from django.core.validators import MinValueValidator

class Lecture(models.Model):
    title = models.CharField(max_length=50)
    slide_count = models.IntegerField(
                    default=1,
                    validators=[MinValueValidator(1)])
    author_username = models.CharField(max_length=10)
    author_forename = models.CharField(max_length=30)
    author_surname = models.CharField(max_length=30)
    session_code = models.CharField(max_length=6, unique=True)
    is_running = models.BooleanField(default=False)
    is_taking_questions = models.BooleanField(default=True)

    def getFirstStartDate(self):
        sessions = self.session_set.all()
        if sessions.exists():
            return sessions.order_by('start_time').first().start_time

    #don't think this function is good or needed, remove?
    def getFirstStartDate_displayStr(self):
        return getFirstStartDate().strftime("%d/%m/%Y, %H:%M")

    @staticmethod
    def getCode():
        code = ""
        for i in range(6):
            code += random.choice(string.ascii_uppercase + string.digits)
        return code

class Session(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    lecture_id = models.ForeignKey(Lecture, on_delete=models.CASCADE)

feedback_system/staff_sessions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import translation
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

from ldap3 import core
from .forms import LoginForm, NewLectureForm
from staff_sessions.models import Lecture, Session

import pdb #pdb.set_trace() to start

# Create your views here.
def login(request):
    context = {}
    #if POST request
    if request.method == 'POST':
        #create a form instance populated with the data sent in the form
        form = LoginForm(request.POST)
        context['form'] = form
        #check provided data is valid
        if form.is_valid():
            #process data form.cleaned_data (ldap authenticate)
            username = form.cleaned_data.get('uid')
            password = form.cleaned_data.get('pswd')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('staff_sessions:index'))
            else:
                # Return an 'invalid login' error message.
                context['login_error'] = True
        else:
            context['invalid_form_error'] = True
    else:
        context['form'] = LoginForm()

    return render(request, 'staff_sessions/login.html', context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('staff_sessions:login'))

@login_required(login_url='/staff/login/')
def index(request):
    previous_lectures = Lecture.objects.filter(author_username=request.user.username).order_by('session__start_time')

    #pagination code
    paginator = Paginator(previous_lectures, 10)
    page = request.GET.get('page')
    try:
        previous_lectures = paginator.page(page)
    except PageNotAnInteger:
        previous_lectures = paginator.page(1)
    except EmptyPage:
        previous_lectures = paginator.page(paginator.num_pages)

    context = {'lecture_list': previous_lectures}
    return render(request, 'staff_sessions/lecture_list.html', context)

@login_required(login_url='/staff/login/')
def lecture_delete(request, id=None):
    instance = get_object_or_404(Lecture, id=id)
    instance.delete()
    return redirect(reverse('staff_sessions:index'))

@login_required(login_url='/staff/login/')
def lecture_new(request):
    context = {}
    #if POST request
    if request.method == 'POST':
        #create a form instance populated with the data sent in the form
        form = NewLectureForm(request.POST)
        context['form'] = form
        #check provided data is valid
        if form.is_valid():
            #process data form.cleaned_data
            #create new lecture from cleaned_data
            title = form.cleaned_data.get('title')
            slide_count = form.cleaned_data.get('slide_count')
            notes = form.cleaned_data.get('notes')

            Lecture.objects.create(title=title,
                                slide_count=slide_count,
                                author_username=request.user.username,
                                author_forename=request.user.first_name,
                                author_surname=request.user.last_name,
                                session_code=Lecture.getCode())
            #redirect to view lecture page (currently back to index)
            return HttpResponseRedirect(reverse('staff_sessions:index'))
        else:
            context['invalid_form_error'] = True
    else:
        context['form'] = NewLectureForm()

    return render(request, 'staff_sessions/lecture_new.html', context)

feedback_system/templates/staff_sessions/lecture_list.html
{% extends 'base_layout.html' %}
{% load i18n %}

{% block title %}
  {% trans "Lecture History" %}
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand mb-0">{% trans "Lecture Feedback System" %} <small>{% if user.is_authenticated %}<strong><u>User</u>:</strong> {{user.get_full_name}} ({{user.email}}){% endif %}</small></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link btn btn-outline-light mr-1" href="{% url 'staff_sessions:lecture_new' %}" role="button">New Session</a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn btn-outline-light ml-1" href="{% url 'staff_sessions:logout' %}" role="button">Logout</a>
          </li>
        </ul>
        <!-- <div class="navbar-nav">
          <a class="nav-link mr-1" href="">New Session</a>
          <a class="nav-link ml-1" href="{% url 'staff_sessions:logout' %}">Logout</a>
        </div> -->
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid bg-light p-3">
     <div class="row">
       <div class="col-sm">
         {% if lecture_list %}
           <ul class="list-group list-group-flush">
             {% for lecture in lecture_list %}
               <li class="list-group-item container-fluid">
                 <div class="row d-flex justify-content-between">
                   <div class="col-sm-auto d-flex flex-column">
                     <div>
                       <a href="#" class="mr-2 h4">{{ lecture.title }}</a>
                     </div>
                     <div>
                       <span class="h5">{{ lecture.getFirstStartDate }}</span>
                     </div>
                   </div>
                   <div class="col-sm-auto">
                     <a href="{% url 'staff_sessions:lecture_delete' lecture.id %}" type="button" class="btn btn-danger my-2 mx-1">Delete</a>
                   </div>
                 </div>
               </li>
             {% endfor %}
            </ul>
          {% else %}
            <h3><center>There are currently no lecture feedback sessions for the logged in user</center></h3>
          {% endif %}
        </div>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="pagination">
            <span class="step-links">
                {% if lecture_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ lecture_list.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ lecture_list.number }} of {{ lecture_list.paginator.num_pages }}.
                </span>

                {% if lecture_list.has_next %}
                    <a href="?page={{ lecture_list.next_page_number }}">next</a>
                    <a href="?page={{ lecture_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
{% endblock %}

feedback_system/templates/staff_sessions/lecture_new.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block title %}
  {% trans "New Lecture" %}
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <span class="navbar-brand mb-0">{% trans "Lecture Feedback System" %} <small>{% if user.is_authenticated %}<strong><u>User</u>:</strong> {{user.get_full_name}} ({{user.email}}){% endif %}</small></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link btn btn-outline-light mr-1" href="{% url 'staff_sessions:index' %}" role="button">History</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-outline-light ml-1" href="{% url 'staff_sessions:logout' %}" role="button">Logout</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container p-3">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-8">
      <form action="{% url 'staff_sessions:lecture_new' %}" method="post" class="bg-light border rounded p-2">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-default">
            {% trans "Create" %}
          </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-auto">
      <form class="bg-light border rounded p-2">
        <div class="form-group">
          <label for="exampleFormControlFile1">Extract from Lecture Slide PDF</label>
          <input type="file" class="form-control-file" id="exampleFormControlFile1">
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

feedback_system/templates/staff_sessions/login.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block title %}
  {% trans "Staff Login" %}
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <span class="navbar-brand mb-0">{% trans "Lecture Feedback System" %} <small>{% if user.is_authenticated %}<strong><u>User</u>:</strong> {{user.get_full_name}} ({{user.email}}){% endif %}</small></span>
</nav>

<div class="container-fluid p-3"">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <form action="{% url 'staff_sessions:login' %}" method="post" class="form border rounded m-4 p-2 bg-light">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Login here if you are a member of staff wishing to start a new feedback session or review a previous one :-)">
            {% bootstrap_icon "star" %} {% trans "Login" %}
          </button>
        {% endbuttons %}
      </form>
    </div>
    <div class="col">
    </div>
  </div>
  {% if user.is_authenticated %}
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="alert alert-primary text-center" role="alert">{% trans "You are already Logged In" %}</div>
    </div>
    <div class="col">
    </div>
  </div>
  {% endif %}
  {% if login_error %}
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="alert alert-danger text-center" role="alert">{% trans "Invalid Staff Login Details" %}</div>
    </div>
    <div class="col">
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}