technical_work/project_code/feedback_system/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]
#append url patterns for different locales
urlpatterns += i18n_patterns(
    path('', include('staff.urls')),
)
# #append url patterns for all cross-app static files
urlpatterns += staticfiles_urlpatterns()
# append patterns for uploaded media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

technical_work/project_code/staff/urls.py
from django.urls import path

from . import views
from staff.views import LectureList, LectureDetail, LectureDelete, LectureCreate, LectureUpdate
#this sets the application namespace so that the {% url %} template tag
#creates links based of the names in this file  for this app
#might be mutliple urls with name='detail' across the project
app_name= 'staff'

#name variable is used to refer to URls to make links in view templates
urlpatterns = [
    #/
    path('', views.connect, name='connect'),
    path('connect/', views.connect, name='connect'),
    path('disconnect/', views.disconnect, name='disconnect'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/new/', views.feedback_create, name='feedback_create'),


    #/login/
    path('login/', views.login, name='login'),
    #/logout/
    path('logout/', views.logout, name='logout'),
    #/lectures/
    path('lectures/', LectureList.as_view(), name="lecture_list"),
    #/lecturs/new/
    path('lecture/new/', LectureCreate.as_view(), name='lecture_create'),
    #/lecture/?
    path('lecture/<int:pk>/', LectureDetail.as_view(), name='lecture_detail'),
    #/lecture/?/feedback_detail
    path('lecture/<int:pk>/feedback_detail/', views.feedback_detail, name='feedback_detail'),
    #/lecture/?/edit/
    path('lecture/<int:pk>/edit/', LectureUpdate.as_view(), name='lecture_update'),
    #/lecture/?/extarct
    path('lecture/<int:pk>/extract/', views.extarct_from_pdf, name='lecture_extarct'),
    #/lecture/?/delete/
    path('lecture/<int:pk>/delete/', LectureDelete.as_view(), name='lecture_delete'),
    #/lecture/?/start_session/
    path('lecture/<int:pk>/session/new/', views.session_new, name='session_new'),
    #lecture/?/file/
    path('lecture/<int:pk>/file/', views.lecture_file_view, name='lecture_file_view'),
    #/session/?/start/
    path('session/<int:pk>/start/', views.session_start, name='session_start'),
    #/session/?/stop/
    path('session/<int:pk>/stop/', views.session_stop, name='session_stop'),
    #/session/?/delete/
    path('session/<int:pk>/delete/', views.session_delete, name='session_delete'),
    #/session/?/merge_with_previous/
    path('session/<int:pk>/merge_with_previous/', views.session_merge_previous, name='session_merge_previous'),
    #/session/?/merge_with_previous/
    path('session/<int:pk>/merge_with_next/', views.session_merge_next, name='session_merge_next'),
    #/lecture/?/generate_session_code/
    path('session/<int:pk>/regenerate_code/', views.session_regenerate_code, name='session_regenerate_code'),
    #/lecture/?/toggle_questions/
    path('session/<int:pk>/toggle_questions/', views.session_toggle_questions, name='session_toggle_questions'),
    #/questions/?/review/
    path('question/<int:pk>/review/', views.question_mark_reviewed, name='question_mark_reviewed'),
    #/questions/?/delete/
    path('question/<int:pk>/delete/', views.question_delete, name='question_delete'),
    #/questions/new/
    path('question/new/', views.question_create, name='question_create'),



    #html reloaded via ajax
    path('session/<int:pk>/questions/', views.session_questions, name='session_questions'),
    path('lecture/<int:pk>/sessions/<str:version>/', views.lecture_sessions, name='lecture_sessions'),


    #probably no longer using these below
    path('api/feedbackdata/', views.session_feedback_chart_data, name='session_feedback_chart_data'),

]

technical_work/project_code/staff/forms.py
from django import forms
from staff.models import Feedback, Lecture
from staff.validators import validate_file_extension
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _

alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters allowed.')

class LoginForm(forms.Form):
    uid = forms.CharField(label=_('Username'), max_length=10, widget=forms.TextInput(attrs={'placeholder': _("Your Username")}))
    pswd = forms.CharField(label=_("Password"), widget=forms.PasswordInput(attrs={'placeholder': _("Your Password")}))

class LectureDetailsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(LectureDetailsForm, self).__init__(*args, **kwargs)
        self.fields['title'].max_length = 150
        self.fields['slide_count'].min_value = 1
        self.fields['notes'].required = False
        self.fields['file'].required = False
        self.fields['file'].validators = [validate_file_extension]

    class Meta:
        model = Lecture
        fields = ['title', 'slide_count', 'notes', 'file',]
        labels = {
            'title': _('Lecture/Workshop Title*'),
            'slide_count': _('Number of Slides*'),
            'notes': _('Extra Notes'),
            'file': _('Lecture PDF')
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': _("Title here..."), 'class': 'form-control'}),
            'slide_count': forms.NumberInput(attrs={'placeholder': _("Slide Count here..."), 'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'placeholder': _("Notes here..."), 'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'})
        }

# class PDFUploadForm(forms.Form):
#     lecture_pdf_file = forms.FileField(label=_('LECTURE FILE'), required=False, validators=[validate_file_extension])

class ConnectForm(forms.Form):
    code = forms.CharField(label=_('Session Code'), min_length=6, max_length=6, validators=[alphanumeric], widget=forms.TextInput(attrs={'placeholder': _("Code here...")}))

class QuestionForm(forms.Form):
    question = forms.CharField(label=_('Ask a question?'), max_length=250, widget=forms.Textarea(attrs={'placeholder': _("Enter a question or comment")}))

class FeedbackForm(forms.ModelForm):

    def __init__(self, lecture, *args, **kwargs): #add in options to exclude!!??
        super(FeedbackForm, self).__init__(*args, **kwargs)
        #build list from number of lecture slides
        choice_list = [(x, 'Slide '+str(x)) for x in range(1,lecture.slide_count+1)]
        #add gneral option for not associating feedback with a specific slide
        choice_list.insert(0, (0,"Not Specified (General Feedback)"))
        self.fields['slide_number'] =  forms.ChoiceField(label=_('Feedback for which slide'), choices=choice_list)

    class Meta:
        model = Feedback
        fields = ['overall_feedback', 'delivery_speed', 'content_complexity', 'content_presentation', 'level_of_engagement', 'slide_number']

technical_work/project_code/staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseNotFound,HttpResponseBadRequest, FileResponse, HttpResponse, Http404
from django.urls import reverse
from django.utils import translation
from django.utils.translation import ugettext as _
from django.utils import timezone
from django.template import RequestContext
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from ldap3 import core
from PyPDF2.utils import PdfReadError
from itertools import chain
import datetime

from staff.forms import LoginForm, LectureDetailsForm, ConnectForm, FeedbackForm, QuestionForm
from staff.models import Lecture, Session, Time, Question, Feedback
from staff.pdf_extractor import get_pdf_pages
from staff.decorators import must_own_lecture, must_own_session, must_own_question
from staff.templatetags.format_extras import runtime_format, question_time_format

import pdb #pdb.set_trace() to start

def get_session_list(request, lecture, per_page):
    """
    Helper method to reduce duplictate Code
    Paginates sessions ready to send to the templates
    """
    context = {'per_page': per_page}
    sessions_queryset = lecture.session_set.all()
    #hack to remove pesky duplicates
    sessions_list = list(dict.fromkeys(list(sessions_queryset)))
    paginator = Paginator(sessions_list, context['per_page'])
    page = request.GET.get('page', paginator.num_pages)
    try:
        context['sessions'] = paginator.page(page)
    except PageNotAnInteger:
        context['sessions'] = paginator.page(paginator.num_pages)
    except EmptyPage:
        context['sessions'] = paginator.page(paginator.num_pages)
    if sessions_list!=[]:
        context['session'] = sessions_list[-1]
    return context

def login(request):
    #pdb.set_trace()
    context = {}
    if request.method == 'POST':
        form = LoginForm(request.POST)
        context['form'] = form
        if form.is_valid():
            username = form.cleaned_data.get('uid')
            password = form.cleaned_data.get('pswd')
            # LDAP Authenticate
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                if 'next' in request.POST and request.POST.get('next')!='':
                    return HttpResponseRedirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect(reverse('staff:lecture_list'))
        else:
            messages.error(request, _('Invalid form data'))
    else:
        context['form'] = LoginForm()

    return render(request, 'staff/login.html', context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('staff:login'))

class LectureList(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Lecture
    paginate_by = 8
    template_name = 'staff/lecture_list.html'

    def get_queryset(self):
        lectures = Lecture.objects.filter(user=self.request.user)
        query = self.request.GET.get("q")
        if query:
            for q in query.split('/'):
                lectures = lectures.filter(
                        Q(title__icontains=q) |
                        Q(date_created__icontains=q))
            messages.success(self.request, "Search Result For: " + query)
        return lectures

@method_decorator(must_own_lecture, name='dispatch')
class LectureDetail(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    model = Lecture
    template_name = 'staff/lecture_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_session_list(self.request, self.get_object(), 5))
        return context

@method_decorator(must_own_lecture, name='dispatch')
class LectureDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Lecture
    success_url =  '/lectures/'

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Lecture Deleted: "+self.get_object().title)
        return super().delete(request, *args, **kwargs)

class LectureCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Lecture
    success_url =  '/lectures/'
    form_class = LectureDetailsForm
    template_name_suffix = '_new'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.file = self.request.FILES.get('file')
        self.object.user = self.request.user
        self.object.save()
        messages.success(self.request, "Lecture Created: " + self.object.title)
        return HttpResponseRedirect(reverse('staff:lecture_list'))

    def form_invalid(self, form):
        messages.error(self.request, _('Invalid form data'))
        return super().form_invalid(form)

@method_decorator(must_own_lecture, name='dispatch')
class LectureUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Lecture
    form_class = LectureDetailsForm
    template_name_suffix = '_edit'

    def get_success_url(self, **kwargs):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.file = self.request.FILES.get('file')
        self.object.save()
        messages.success(self.request, "Lecture Updated")
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, _('Invalid form data'))
        return super().form_invalid(form)

@must_own_lecture
@login_required(login_url='/login/')
def extarct_from_pdf(request, pk=None):
    """
    Extarcts the number of slides of a lecture from a PDF of the lecture slides
    Useful incase users are unsure of the number of slides in the presentation they are giving
    """
    lecture = get_object_or_404(Lecture, id=pk)
    if lecture.file:
        lecture.slide_count = get_pdf_pages(lecture.file)
        lecture.save()
        messages.success(request, _("Slide count extracted from uploaded PDF file") + ' (' + str(lecture.slide_count) + ')')
    else:
        messages.error(request, _("There is no PDF associated with this lecture"))
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': lecture.id}))

def lecture_file_view(request, pk=None):
    lecture = get_object_or_404(Lecture, id=pk)
    try:
        filename = lecture.file.path
        if request.user.is_authenticated and lecture.user==request.user:
            return FileResponse(open(filename, 'rb'), content_type='application/pdf')
        elif lecture==Session.objects.get(pk=request.session['connected_session_id']).lecture:
            return FileResponse(open(filename, 'rb'), content_type='application/pdf')
        else:
            return HttpResponse('Unauthorized', status=401)

    except (KeyError, Session.DoesNotExist):
        messages.error(request, _('Please connect to active session with valid feedback code'))
        return redirect(reverse('staff:connect'))
    except ValueError:
        raise Http404
    except FileNotFoundError:
        raise Http404

@must_own_lecture
@login_required(login_url='/login/')
def session_new(request, pk=None):
    lecture = get_object_or_404(Lecture, id=pk)
    lecture.session_set.create(code=Session.generate_code())
    messages.success(request, _('Created New Session'))
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': pk}))

@must_own_session
@login_required(login_url='/login/')
def session_start(request, pk=None):
    session = get_object_or_404(Session, id=pk)
    if session.is_running:
        messages.error(request, _('Session') + ' ' + str(session) + ': ' + _('Already running'))
    else:
        session.is_running = True
        session.save()
        Time.objects.create(start=timezone.now(), session=session)
        messages.success(request, _('Session') + ' ' + str(session) + ': ' + _('Started'))
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': session.lecture.id}))

@must_own_session
@login_required(login_url='/login/')
def session_stop(request, pk=None):
    session = get_object_or_404(Session, id=pk)
    if session.is_running:
        session.is_running = False #set session as no longer running
        session.end() #update end_time
        session.save()
    messages.success(request, _('Session') + ' ' + str(session) + ': ' + _('Ended'))
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': session.lecture.id}))

@must_own_session
@login_required(login_url='/login/')
def session_delete(request, pk=None):
    session = get_object_or_404(Session, id=pk)
    session.delete()
    messages.success(request, _('Session') + ' ' + str(session) + ': ' + _('Deleted'))
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': session.lecture.id}))

@must_own_session
@login_required(login_url='/login/')
def session_merge_previous(request, pk=None):
    session = get_object_or_404(Session, id=pk)
    session.merge('previous')
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': session.lecture.id}))

@must_own_session
@login_required(login_url='/login/')
def session_merge_next(request, pk=None):
    session = get_object_or_404(Session, id=pk)
    session.merge('next')
    return redirect(reverse('staff:lecture_detail', kwargs={'pk': session.lecture.id}))

@must_own_session
@login_required(login_url='/login/')

technical_work/project_code/templates/staff/lecture_detail.html
{% extends 'base_layout.html' %}
{% load static %}
{% load i18n %}
<!-- {% load bootstrap3 %} -->
{% load format_extras %}

{% block title %}{% trans "Lecture Feedback Detail" %}{% endblock %}


{% block script %}
<script src="{% static 'js/lecture_detail.js' %}"></script>
{% endblock %}

{% block nav_options %}

<div class="shift-nav">
  <ul class="navbar-nav mr-auto d-flex flex-row">
    {% if lecture.file %}
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:lecture_file_view' lecture.id %}" role="button">{% trans "View Lecture PDF" %}</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:feedback_detail' lecture.id %}" role="button">{% trans "View Feedback" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:lecture_list' %}" role="button">{% trans "Lecture List" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:logout' %}" role="button">{% trans "Logout" %}</a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid bg-light h-100">
  <div class="row h-100">
    <div class="col-sm-3 pt-3 text-white bg-dark">
      <a id="new_session_link" href="{% url 'staff:session_new' lecture.id %}" role="button" id="newSessionBtn" class="btn btn-block btn-lg btn-success mr-4">{% trans "Create Session For Feedback" %}</a>
      <div class="my-3"></div>

      <hr class="border border-white"/>
      <div class="">
        <label for="exampleFormControl1" class="h6">{% trans "Title" %}</label><a href="{% url 'staff:lecture_update' lecture.id %}" title="Edit this lecture's details" class="float-right">{% trans 'Edit' %}</a>
        <input class="form-control " id="exampleFormControl1" type="text" placeholder="{{lecture.title}}" readonly>
        <label for="exampleFormControl2" class="h6">{% trans "Owner" %}</label>
        <input class="form-control" id="exampleFormControl2" type="text" placeholder="{{lecture.user.get_full_name}} {{lecture.user.email}}" readonly>
        <label for="exampleFormControl3" class="h6">{% trans "No. Slides" %}</label><a href="{% url 'staff:lecture_extarct' lecture.id %}" title="Extract the lecture slide count from file" class="float-right">{% trans 'Extract slide count from PDF' %}</a>
        <input class="form-control" id="exampleFormControl3" type="text" placeholder="{{lecture.slide_count}}" readonly>
        <label for="notesArea" class="h6">{% trans "Notes" %}</label>
        <textarea name="name" rows="8" cols="80" class="form-control" id="notesArea" type="text" placeholder="{{lecture.notes}}" readonly></textarea>
      </div>
      <hr class="border border-white"/>
      <div id="actionsPanel">
        <h5>{% trans 'Click on a Session Row' %}</h5>
      </div>
    </div>
    <div class="col-sm-9 pt-3 bg-light">
        <div>
          {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <div class="alert alert-success text-center float-right" role="alert">{{ message }}</div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
              <div class="alert alert-warning text-center float-right" role="alert">{{ message }}</div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <div class="alert alert-danger text-center float-right" role="alert">{{ message }}</div>
            {% endif %}
          {% endfor %}
        </div>
        <div class="remember_visibility" id="sessionDiv">
          {% include 'staff/lecture_sessions_list.html' %}
        </div>
        <hr />
        {% if sessions %}
          <div class=" remember_visibility" id="questionDiv">
            {% include 'staff/questions_list.html' %}
          </div>
        {% endif %}
    </div>
  </div>
</div>
<input type="hidden" id="lectureID" name="lecture" value="{{ lecture.id }}">
{% endblock %}

technical_work/project_code/templates/staff/lecture_edit.html
{% extends 'base_layout.html' %}
{% load i18n %}

{% block title %}{% trans "Edit Lecture" %}{% endblock %}

{% block nav_options %}
<div class="shift-nav">
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:lecture_detail' lecture.id %}" role="button">{% trans "Lecture Detail" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:logout' %}" role="button">{% trans "Logout" %}</a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="container p-3">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-8">
      <form action="{% url 'staff:lecture_update' lecture.id  %}" enctype="multipart/form-data" method="post" class="bg-light border rounded p-2">
        {% csrf_token %}
        {{ form }}
          <button type="submit" class="btn btn-default mt-2">
            {% trans "Update" %}
          </button>
      </form>
    </div>
  </div>

  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-danger text-center" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

technical_work/project_code/templates/staff/lecture_edit_form.html
{% load i18n %}
<html>

<head>
  <title>{% trans "New Lecture" %}</title>
</head>

<body>
  <form action="{% templatetag openblock %} url 'staff:lecture_update' lecture.id {% templatetag closeblock %}" method="post" class="bg-light border rounded p-2">
    {% csrf_token %}
    {% form %}
    <button type="submit" class="btn btn-default">{% trans "Update" %}</button>
  </form>
</body>

</html>

technical_work/project_code/templates/staff/lecture_new.html
{% extends 'base_layout.html' %}
{% load i18n %}

{% block title %}{% trans "New Lecture" %}{% endblock %}

{% block nav_options %}
<div class="shift-nav">
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:lecture_list' %}" role="button">{% trans "Lecture List" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'staff:logout' %}" role="button">{% trans "Logout" %}</a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="container p-3">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-8">
      <form action="{% url 'staff:lecture_create' %}" enctype="multipart/form-data" method="post" class="bg-light border rounded p-2">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-default mt-2">
          {% trans "Create" %}
        </button>
      </form>
    </div>
  </div>

  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-danger text-center" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

technical_work/project_code/templates/staff/lecture_sessions_list.html
{% load i18n %}
{% load format_extras %}

{% if sessions %}
<h3 class="">{% trans "Feedback Sessions" %}</h3>
<div class="table-responsive">
  <table id="session_table" class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">{% trans "Session" %}</th>
        <th scope="col">{% trans "Code" %}</th>
        <th scope="col">{% trans "First Startime" %}</th>
        <th scope="col">{% trans "Last Endtime" %}</th>
        <th scope="col">{% trans "Runtime" %}</th>
      </tr>
    </thead>
    <tbody class="bg-light">
      {% for session in sessions %}
      <tr id="{{ session.id }}" class="session_row">
        <th><div class="bg-light p-1 border rounded">{% session_numbering forloop.counter sessions.number per_page %}</div></th>
        <td><div class="bg-light p-1 border rounded">{{ session.code }}</div></td>
        <td><div class="bg-light p-1 border rounded" title="{% for time in session.time_set.all %}{% if forloop.first %}Start Times:&#013;{% endif %}{{ time.start }}&#013;{% endfor %}">
          {% if session.get_first_start_time %}
            {{ session.get_first_start_time|date:'d M, Y - h:i a' }}
          {% else %}
            N/A
          {% endif %}
        </div></td>
        {% if session.is_running %}
          <td><div class="bg-light p-1 border rounded">{% trans "Session Running" %}</div></td>
        {% else %}
          <td><div class="bg-light p-1 border rounded" title="{% for time in session.time_set.all %}{% if forloop.first %}End Times:&#013;{% endif %}{{ time.end }}&#013;{% endfor %}">
            {% if session.get_last_end_time %}
              {{ session.get_last_end_time|date:'d M, Y - h:i a' }}
            {% else %}
              N/A
            {% endif %}
          </div></td>
        {% endif %}
        <td class="time"><div class="bg-light p-1 border rounded">{{ session.get_total_runtime|runtime_format }}</div></td>
        <td class="d-none">
          <div class="bg-light p-1 border rounded options">
            {% if session.is_running %}
            <div class="d-flex flex-row">
              <a id="stop_session_link" href="{% url 'staff:session_stop' session.id %}" role="button" class="btn btn-block btn-lg btn-warning m-2">{% trans "End Session" %}</a>
            </div>
            {% else %}
            <div class="d-flex flex-row">
              <a id="start_session_link" href="{% url 'staff:session_start' session.id %}" role="button" class="btn btn-block btn-lg btn-success m-2">{% trans "Start Session" %}</a>
            </div>
            {% endif %}
            <div class="d-flex flex-row">
              {% if not forloop.first %}<a href="{% url 'staff:session_merge_previous' session.id %}" role="button" class="btn btn-block btn-primary m-1">{% trans "Merge with Above Session" %}</a><br />{% endif %}
              {% if not forloop.last %}<a href="{% url 'staff:session_merge_next' session.id %}" role="button" class="btn btn-block btn-primary m-1">{% trans "Merge with Below Session" %}</a><br />{% endif %}
            </div>
            <div class="d-flex flex-row">
              <a href="{% url 'staff:session_toggle_questions' session.id %}" role="button" class="btn btn-block btn-secondary m-1">
                {% if session.is_taking_questions %}
                  {% trans "Disable" %}
                {% else %}
                  {% trans "Enable" %}
                {% endif %}
                 {% trans "Questions" %}</a><br />
              <a href="{% url 'staff:session_regenerate_code' session.id %}" role="button" class="btn btn-block btn-secondary m-1">{% trans "Generate New Code" %}</a><br />
            </div>
            <div class="d-flex flex-row">
              <a href="{% url 'staff:session_delete' session.id %}" role="button" class="btn btn-block btn-danger m-1">{% trans "Delete Session" %}</a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if sessions.has_previous %}
            <a class="pagination_link" href="?page=1">&laquo; first</a>
            <a class="pagination_link" href="?page={{ sessions.previous_page_number }}">previous</a>
        {% endif %}

        <span id="session_page" class="current" value="{{ sessions.number }}">
            {% trans "Page" %} {{ sessions.number }} {% trans "of" %} {{ sessions.paginator.num_pages }}.
        </span>

        {% if sessions.has_next %}
            <a class="pagination_link" href="?page={{ sessions.next_page_number }}">next</a>
            <a class="pagination_link" href="?page={{ sessions.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% else %}
  <div class="alert alert-secondary m-5" role="alert"><center>
    <h1 class="display-1 border border-top border-bottom">{% trans 'No Sessions' %}</h1>
  </center></div>
{% endif %}